### PR TITLE
Added GeForce Experience (Nvidia)

### PR DESCRIPTION
**Pull request by guiweber**

### CODE REVIEW

**Comment by lvillani** [comment]
I used to have nVidia drivers in the registry before but then removed them because they are updated way too often (and Windows installs, and then updates, the proper WHQL driver as soon as it connects to the Internet anyway).

GeForce Experience is similarly updated every other week and I'd prefer to have a link to always download the latest stable release since it becomes stale pretty quickly.

**Comment by lvillani** [comment]
On second thought, I'm merging this anyway.

**Comment by lvillani** [comment]
Merged manually, closing.

**Comment by guiweber** [comment]
Actually I've been thinking... updating the catalog manually is definitely not the most efficient thing to do.

Have you thought about fetching the download links from the official web pages instead of keeping them in the registry? The registry could contain a link to the page and an xpath or a css selector to the element with the link. Most application webpages have a big download button with a link to the latest version, so conceptually it doesn't seem too complicated, and all links would always be up-to-date. I am however not familiar with the Go ecosystem at all, so I don't know how easy parsing a web page would be.

Alternatively, there could be an external script (in another language) that you run once a day to update the master registry file. This could easily be done in Nodejs.

**Pull request closed without merging**
