### PR TITLE
Add google-drive package

### PR DESCRIPTION
**Pull request by Infuriare**

### CODE REVIEW

**Comment by guiweber** [comment]
@Infuriare The download link seems to point to the enterprise version of google drive. The entry name should probably be changed to reflect this to avoid any confusion with the regular google drive app.

**Comment by Infuriare** [comment]
My reasoning behind this is due to the regular Google Drive installer being a .exe that is an online installer and does not seem to be able to be run silently, however, the enterprise version is an .msi that runs silently by default and as far as I can tell installs the exact same version of Google Drive.

Although I'm more than happy to change the name as you see fit.

**Comment by guiweber** [comment]
Good point. If it's the same app, then it does make sense to keep the entry as-is.

**Comment by lvillani** [comment]
Note that we also use the enterprise installer for Google Chrome

**Pull request merged**
