### PR TITLE
Use latest stable as jom version

### PR DESCRIPTION
**Pull request by naufraghi**

### CODE REVIEW

**Comment by lvillani** [comment]
Can you rebase this against master? This PR contains stuff also sent as part of PR #67

**Comment by naufraghi** [comment]
Ok, as a side note, this was the crash "message":

```
Z:\>just-install jom
2015/04/15 14:56:03 x86_64 - http://download.qt-project.org/official_releases/jom/jom_1_0_14.zip
panic: interface conversion: interface is nil, not string

goroutine 16 [running]:
runtime.panic(0x653320, 0x12c16a00)
        c:/go/src/pkg/runtime/panic.c:279 +0xe9
main.(*registryEntry).install(0x12bf7e60, 0x12bf8f00, 0x31)
        C:/Users/Lorenzo/Development/Go/src/github.com/lvillani/just-install/just-install.go:362 +0xa60
main.(*registryEntry).JustInstall(0x12bf7e60, 0x12c16100, 0x6897d8, 0x6)
        C:/Users/Lorenzo/Development/Go/src/github.com/lvillani/just-install/just-install.go:294 +0x518
main.handleArguments(0x12c023c0)
        C:/Users/Lorenzo/Development/Go/src/github.com/lvillani/just-install/just-install.go:169 +0x21c
github.com/codegangsta/cli.(*App).Run(0x12c20000, 0x12bf00f0, 0x2, 0x2, 0x0, 0x0)
        C:/Users/Lorenzo/Development/Go/src/github.com/codegangsta/cli/app.go:135 +0x821
main.handleCommandLine()
        C:/Users/Lorenzo/Development/Go/src/github.com/lvillani/just-install/just-install.go:136 +0x247
main.main()
        C:/Users/Lorenzo/Development/Go/src/github.com/lvillani/just-install/just-install.go:58 +0x2b

goroutine 17 [runnable]:
runtime.MHeap_Scavenger()
        c:/go/src/pkg/runtime/mheap.c:507
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 18 [runnable]:
bgsweep()
        c:/go/src/pkg/runtime/mgc0.c:1976
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445

goroutine 19 [runnable]:
runfinq()
        c:/go/src/pkg/runtime/mgc0.c:2606
runtime.goexit()
        c:/go/src/pkg/runtime/proc.c:1445
```

**Comment by lvillani** [comment]
The entry is missing the "destination" option. See another similar entry to take as example: https://github.com/lvillani/just-install/blob/9d90af2c973264937bf592627933cbb978dc6a70/just-install.json#L156-L165

**Comment by naufraghi** [comment]
Done, with added 'destination' and 'shims' too

**Comment by lvillani** [comment]
Great! Thanks! :+1:

**Pull request merged**
