### PR TITLE
Add multiple eclipse packages

### PR DESCRIPTION
**Pull request by Infuriare**

### CODE REVIEW

**Comment by guiweber** [comment]
@Infuriare If you have time, it would be great if you could add rules to the [updater](https://github.com/guiweber/just-install-updater/) as well, in order to keep these entries up-to-date.

**Comment by lvillani** [comment]
I'm adding these packages as-is for now even though:
1. Download links are not versioned (well their version is "neon" which roughly correspond with version "4.6" we are using).
2. As soon as these packages become too old, they'll probably have to be removed from the catalog.

**Comment by guiweber** [comment]
@lvillani did you close this PR by mistake? Just asking since you said you were adding the packages as-is.

Even though they are not versioned, I can easily check and fetch the latest version with the updater, so they won't become obsolete.

**Comment by lvillani** [comment]
Merged.

**Pull request merged**
