### PR TITLE
SW added

### PR DESCRIPTION
**Pull request by suoko**
lifesizecloud and hipchat added

### CODE REVIEW

**Comment by lvillani** [comment]
This commit reformats the entire file and I can't merge it as-is. Can you rework it so that the diff makes sense?

**Comment by suoko** [comment]
I noticed that something strange happened. It's like I changed almost half of the file instead of adding a few lines. Gotta change editor and try again

**Comment by suoko** [comment]
Check now.
Changes now reflects the actual number of added lines.


Gabriele
http://about.me/gabrielev

2016-07-07 10:45 GMT+02:00 Lorenzo Villani <notifications@github.com>:

**Comment by lvillani** [comment]
Can you squash both commits in a single one?

**Comment by suoko** [comment]
You got One single commit now

**Comment by lvillani** [comment]
I still see two commits in this PR

**Comment by lvillani** [comment]
Also, please, don't open a new pull request each time you commit changes.

**Comment by lvillani** [comment]
I'm closing this one due to lack of follow-up. Feel free to re-open as necessary.

**Comment by suoko** [comment]
Hi,

I solved everything in the last commit. Did you see it?

Il 18 lug 2016 10:25, "Lorenzo Villani" <notifications@github.com> ha
scritto:

**Comment by lvillani** [comment]
Nope, this PR is still made up of two commits, one that changes the entire `just-install.json` file and one, that builds upon the previous one, that makes the actual change. Please rebase the PR to remove the offending commit or open a new PR with just the necessary changes.

**Comment by suoko** [comment]
commit

**Pull request closed without merging**
